services:
  # clickhouse:
  #   image: docker.io/clickhouse:25.7.4.11
  #   ports:
  #     - "8123:8123"
  #     - "9000:9000"
  #   environment:
  #     CLICKHOUSE_USER: clickhouse
  #     CLICKHOUSE_PASSWORD: clickhouse
  #   volumes:
  #     - starling_dev_clickhouse_data:/var/lib/clickhouse/
  db:
    image: docker.io/postgres:17.4-bullseye
    environment:
      POSTGRES_DB: starling_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - starling_dev_data:/var/lib/postgresql/data

volumes:
  starling_dev_data:
  # starling_dev_clickhouse_data:
